name=input("Enter your name : ")
door_num=input("Enter your Door Number : ")
block_name=input("Enter your Block Name : ")
street_name=input("Enter your Street Name : ")
area=input("Enter your Area : ")
post=input("Enter your Post : ")
district=input("Enter your District : ")
pin_code=input("Enter your Pin Code : ")
print("Name :" , name)
print("Door Number : " ,door_num)
print("Block Name : " , block_name)
print("Street Name : " , street_name)
print("Area : " , area)
print("Post : " , post)
print("District : " , district)
print("Pin Code : " , pin_code)
