name=" Harshitaa Prabu "
print(name.capitalize())
print(name.center(100))
print(name.count("a"))
print(name.isupper())
print(name.lower())
print(name.upper())
print(name.isalnum())
print(name.isalpha())
print(name.islower())
print(name.isnumeric())
print(name.isdigit())
print(name.strip())
print(name.lstrip())
print(name.rstrip())
print(name.split("a"))
print(name.replace("Harshitaa","Harshitha"))